version: '3'
services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftpd_server
    restart: always      
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./remote/files:/home/files  #Modify this line with the remote directory (to mount the volume)
      - ./ftp/passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: ${FTP_USER_HOME}
      ADDED_FLAGS: "-d -d"